[project]
name = "python-bootstrap"
version = "0.1.0"
description = "Template for quickly bootstrapping Python projects"
requires-python = ">=3.11"

[tool.uv]
dev-dependencies = [
  "pytest",
  "pre-commit",
  "ruff",
  "black"
]
